---
- name: Set generic network/interfaces
  template:
    src=interfaces.j2
    dest=/etc/network/interfaces
    mode=0644
    owner=root
    group=root

- name: Set interfaces up
  template:
    src=interface.j2
    dest=/etc/network/interfaces.d/{{ item.key }}
    mode=0644
    owner=root
    group=root
  with_dict: deb_network

# vim ft=ansible
