---
- fail: msg="Missing 'deb_network' variable"
  when: deb_network is undefined

- name: Install networking packages
  apt: name={{ item }}
       state=present
  with_items:
    - bridge-utils
    - bwm-ng
    - dhcpdump
    - ifupdown
    - iproute2
    - iptraf-ng
    - nmap
    - tcpdump
    - vlan
  tags:
    - packages
    - networking

- name: Load 8021q module at runtime
  modprobe: name=8021q state=present
  tags:
    - kernel
    - networking

- name: Load 8021q module at boot time
  lineinfile: dest=/etc/modules
              state=present
              line=8021q
              regexp='^8021q\s*(#.*)?$'
  tags:
    - kernel
    - networking

- name: Set VLAN name type
  command: /sbin/vconfig set_name_type {{ vlan_name_type }}
  tags:
    - kernel
    - networking

- name: Set blank /etc/network/interfaces file
  template:
    src=interfaces.j2
    dest=/etc/network/interfaces
    mode=0644
    owner=root
    group=root

- name: Define networking parameters
  template:
    src=interface.j2
    dest=/etc/network/interfaces.d/{{ item.key }}.cfg
    mode=0644
    owner=root
    group=root
  register: iface_result
  with_dict: "{{ deb_network }}"
  tags:
    - config
    - networking

- name: Cycle network interfaces
  shell: (timeout {{ iface_cycle_timeout.ifdown }} ifdown {{ item.item.key }}; timeout {{ iface_cycle_timeout.ifup }} ifup {{ item.item.key }}) || /bin/true
  with_items: "{{ iface_result.results }}"
  when: iface_result is defined and item.changed

# vim: ft=ansible
